# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build x86
      run: GOARCH=amd64 go build -o ./autostop/autostop-x86_64 ./autostop/autostop.go
    - name: Build x86
      run: GOARCH=arm64 go build -o ./autostop/autostop-arm64 ./autostop/autostop.go
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
            autostop/autostop-x86_64
            autostop/autostop-arm64
            autostop/autostop.service
